# Dockerfile for Natuzap Backend
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY ./backend/package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY ./backend/dist ./dist

# Expose port
EXPOSE 3000

# Start the application
CMD [ "node", "dist/main.js" ]